/**
 * Created by helion on 19/03/16.
 */
export const VIEWS_SELECT_TAB = 'VIEWS_SELECT_TAB';
export const BACKEND_TV_FOUND = 'BACKEND_TV_FOUND';
export const BACKEND_PAIR_DISCONNECTED = 'BACKEND_PAIR_DISCONNECTED';

export const CREATEVOTE_ADD_ANSWER = 'CREATEVOTE_ADD_ANSWER';
export const CREATEVOTE_SET_ANSWER = 'CREATEVOTE_SET_ANSWER';
export const CREATEVOTE_SET_QUESTION = 'CREATEVOTE_SET_QUESTION';
export const CREATEVOTE_SAVE_VOTE = 'CREATEVOTE_SAVE_VOTE';

export const CHAT_ADD_MESSAGE = 'CHAT_ADD_MESSAGE';