/**
 * Created by helion on 19/03/16.
 */
export const VIEWS_SELECT_TAB = 'VIEWS_SELECT_TAB';
export const BACKEND_TV_FOUND = 'BACKEND_TV_FOUND';
export const BACKEND_PAIR_DISCONNECTED = 'BACKEND_PAIR_DISCONNECTED';